import { PRICING, type BookCategory, type BookSize, type LaunchMode } from "./site";

export type PageNote = {
  tone: "navy" | "green" | "red";
  title: string;
  text: string;
};

export type BookPage = {
  heading: string;
  body: string[];
  note?: PageNote;
  bullets?: string[];
};

export type CatalogBook = {
  slug: string;
  title: string;
  subtitle: string;
  seriesNo: string;
  category: BookCategory;
  size: BookSize;
  launchMode: LaunchMode;
  coverUrl: string;
  blurb: string;
  pages: BookPage[];
};

const author = "O.J. Alonge";

function onlinePrice(size: BookSize) {
  return PRICING.online[size] * 100;
}

export const CATALOG: CatalogBook[] = [
  {
    slug: "synthetic-indices-101",
    title: "Synthetic Indices",
    subtitle: "101",
    seriesNo: "101",
    category: "Synthetic Indices",
    size: "full",
    launchMode: "prelaunch",
    coverUrl: "/covers/synthetic-indices-101.png",
    blurb:
      "The complete starting map for Volatility, Boom & Crash, Step, Jump, and Range. Written for traders who want the market that never sleeps — without the folklore.",
    pages: [
      {
        heading: "The market that never sleeps",
        body: [
          "Synthetic indices are not stocks, not forex pairs, and not a casino side-game. They are independently generated markets that move around the clock, with published volatility behaviour you can study like any other chart.",
          "This guide is the orientation most traders skip. You will leave knowing what you are looking at, why the candles look the way they do, and which book in this library to open next.",
        ],
        note: {
          tone: "navy",
          title: "Read this first",
          text: "Nothing here is a signal, a promise, or financial advice. It is market literacy for people who already know that risk of loss is real.",
        },
      },
      {
        heading: "What “synthetic” actually means",
        body: [
          "A synthetic index is generated by a proprietary algorithm. It is not tied to a company’s earnings, a central-bank meeting, or a news headline. That is the point: the chart is always open, and the behaviour is designed to be statistically consistent over time.",
          "Because there is no underlying asset, you are trading price behaviour itself — volatility clusters, spikes, steps, and ranges. Your edge, if you ever have one, comes from process: selection, size, and patience.",
        ],
        bullets: [
          "24/7 session — no New York open to hide behind",
          "Behaviour is published by family (Volatility, Boom & Crash, Step, Jump, Range)",
          "Spreads and contract specs still matter. Chart beauty is not a fill.",
        ],
      },
      {
        heading: "The five families",
        body: [
          "Volatility indices trend and range like a restless forex pair, with a named volatility level (10, 25, 50, 75, 100 and the 1s variants).",
          "Boom & Crash are spike markets. Boom prints sudden up-spikes; Crash prints sudden down-spikes. Most of the session is the grind between those events.",
          "Step Index advances in visible increments. Jump Index gaps. Range Break waits at a band, then runs. Each family punishes a different kind of impatience.",
        ],
        note: {
          tone: "green",
          title: "Series map",
          text: "Volatility Mastery, Boom & Crash, Step Index, and Jump Indices each get their own book. This 101 is the hallway that connects them.",
        },
      },
      {
        heading: "Timeframes that tell the truth",
        body: [
          "Synthetic markets look noisy on the 1-minute chart and almost civil on the 15-minute and 1-hour. New traders live on the lowest timeframe because it feels like “action.” Professionals zoom out until the structure is obvious, then drop down only to time the entry.",
          "A useful habit: mark bias on H1, locate the level on M15, execute on M5 or M1. If the higher timeframe is a mess, you do not have a trade. You have entertainment.",
        ],
      },
      {
        heading: "Sessions without a session",
        body: [
          "There is no London open. There is still a human clock. Liquidity from the people trading these markets still clusters around waking hours in Africa, South Asia, and late US evenings.",
          "That does not make a “best time” gospel. It means you should log your own hours for thirty days before you decide the market is “manipulated.” Most of what feels like targeting is position size meeting a normal spike.",
        ],
        note: {
          tone: "red",
          title: "A hard rule",
          text: "If you cannot name your max loss in account currency before the click, you are not trading. You are hoping.",
        },
      },
      {
        heading: "Lot size is the real strategy",
        body: [
          "The formula on the cover of this book is not decoration: Lot Size = Risk ÷ (SL × Pip Value). Until that is automatic, every other chapter is trivia.",
          "Synthetic indices can travel. A Crash spike does not care that your stop “looks tight on this zoom.” Size the trade as if the spike will hunt the obvious stop — because sometimes it will.",
        ],
      },
      {
        heading: "How to use The Trading Library",
        body: [
          "Read 101 once. Then pick the family you actually trade. Do not collect titles like trophies.",
          "Risk & Lot Size is mandatory. Psychology is mandatory after your first two ugly weeks. Patterns and Supply & Demand are tools, not personalities.",
        ],
        bullets: [
          "Tagged SLT members: generate your coupon from the account page during pre-launch.",
          "Online reading is watermarked to your name and CR. Treat it like a desk copy, not a PDF to forward.",
          "Downloads are always paid. That is how the library stays alive.",
        ],
      },
      {
        heading: "Before you place the next trade",
        body: [
          "Write a one-page contract with yourself: markets you are allowed to trade, hours you are allowed to sit, risk per trade, max trades per day, and what you will do after a loss.",
          "Then close this book and open Risk & Lot Size. Literacy without size is how accounts disappear on a market that never closes.",
        ],
      },
    ],
  },
  {
    slug: "risk-lot-size",
    title: "Risk & Lot Size",
    subtitle: "Position Sizing",
    seriesNo: "02",
    category: "Risk & Lot Size",
    size: "short",
    launchMode: "prelaunch",
    coverUrl: "/covers/risk-lot-size.jpg",
    blurb:
      "The handbook that keeps you in the game. Position size, drawdown math, and the stop-loss arithmetic synthetic traders skip until it is too late.",
    pages: [
      {
        heading: "Survival is the edge",
        body: [
          "You do not need a holy grail. You need to still have an account in six months. That is the entire thesis of this handbook.",
          "Risk is not a percentage you quote in a group chat. It is a number in your deposit currency that you can lose today without changing how you sleep.",
        ],
      },
      {
        heading: "The formula",
        body: [
          "Lot Size = Risk amount ÷ (Stop-loss distance × value per unit). If any input is a guess, the lot size is a guess.",
          "On synthetic indices, “pip value” changes with the contract. Check the specification on your platform for the index you are actually trading — V75 is not Crash 500. Never reuse yesterday’s lot on a new market.",
        ],
        note: {
          tone: "navy",
          title: "Worked example",
          text: "Account $250. Risk 1% = $2.50. Stop is 400 points. If each 0.001 lot risks about $0.40 on that stop, you do not belong on 0.1. You belong on the smallest size that still makes the math true.",
        },
      },
      {
        heading: "Stops that mean something",
        body: [
          "A stop under the last candle is not a stop. A stop beyond the structure that invalidates the idea is a stop.",
          "If that distance is too wide for your risk amount, you do not widen hope. You cut size, or you pass. Passing is a position.",
        ],
      },
      {
        heading: "Drawdown is a sequence",
        body: [
          "Five losses in a row at 2% is not a 10% story in the way people think — compounding and recovery percentages hurt more than the round number.",
          "Cap daily loss. Cap weekly loss. When the cap hits, you shut the platform. That rule has saved more accounts than any indicator in this library.",
        ],
        bullets: [
          "0.5–1% risk per idea on small accounts",
          "Hard daily stop: 2–3R, then done",
          "No ‘make it back’ trade. That trade is how 3R becomes 8R.",
        ],
      },
      {
        heading: "Spikes and your stop",
        body: [
          "Boom, Crash, and Jump will pass through prices you thought were safe. Size as if they will. If a spike taking your stop would ruin the week, the lot is too big — even if the setup is beautiful.",
        ],
        note: {
          tone: "red",
          title: "Account killer",
          text: "Martingale on synthetic spikes is not a strategy. It is a countdown.",
        },
      },
      {
        heading: "The desk card",
        body: [
          "Print one card: risk amount, max lots per market, daily cap, and the sentence “If I cannot size it, I do not take it.” Keep it on the screen bezel.",
          "Reread this handbook any week you feel invincible. That feeling is usually late in a lucky streak.",
        ],
      },
    ],
  },
  {
    slug: "supply-demand",
    title: "Supply & Demand",
    subtitle: "Zones That Matter",
    seriesNo: "03",
    category: "Supply & Demand",
    size: "medium",
    launchMode: "prelaunch",
    coverUrl: "/covers/supply-demand.jpg",
    blurb:
      "How to mark the levels synthetic indices actually react from — fresh zones, leftover liquidity, and the difference between a level and a wish.",
    pages: [
      {
        heading: "Price remembers imbalance",
        body: [
          "A supply zone is where price left in a hurry because sellers overwhelmed buyers. A demand zone is the opposite. You are not drawing boxes for art. You are marking where the last unfinished business still sits.",
        ],
      },
      {
        heading: "Fresh versus used",
        body: [
          "The first return to a zone is the one worth planning. The third visit is often someone else’s leftover. If the zone has been chewed through, it is not a zone anymore. It is history.",
        ],
        bullets: [
          "Base → departure with displacement",
          "Unmitigated (fresh) gets priority",
          "Confluence with a higher-timeframe level beats a pretty M1 box",
        ],
      },
      {
        heading: "How to draw without lying",
        body: [
          "Use the body of the base candles, not the most extreme wick you can find so the box “looks like it worked” on the last swing. If you need the wick to make the story true, the zone is not the reason the trade worked.",
        ],
        note: {
          tone: "green",
          title: "Checklist",
          text: "Departure candle closes beyond the base. Gap or strong body. Higher timeframe agrees. Then — and only then — drop to execution.",
        },
      },
      {
        heading: "Synthetic-specific noise",
        body: [
          "Volatility indices will wick zones and still respect them. Boom & Crash will spike through a zone and never look back. Do not copy-paste forex zone rules onto Crash 1000 and call it a system.",
        ],
      },
      {
        heading: "Entries that wait",
        body: [
          "Let price come to the zone. Chasing a departure candle is how you buy the top of a spike. Set the alert. Walk away. If you miss it, you missed it. There is another zone tomorrow — this market does not close.",
        ],
      },
      {
        heading: "When to skip the zone",
        body: [
          "News-like spikes (even without news), overlapping bases, and zones sitting in the middle of a range are optional. Optional means no. Your job is to select, not to participate.",
        ],
      },
    ],
  },
  {
    slug: "chart-patterns",
    title: "Chart Patterns",
    subtitle: "Structure over hope",
    seriesNo: "04",
    category: "Chart Patterns",
    size: "medium",
    launchMode: "prelaunch",
    coverUrl: "/covers/chart-patterns.jpg",
    blurb:
      "Candles, structure, continuation and breaks — a practical pattern book for synthetic charts, without the 47-pattern trivia deck.",
    pages: [
      {
        heading: "Patterns are language, not spells",
        body: [
          "A pin bar in a vacuum is a candle. A pin bar at a daily demand zone after a washout is a sentence. This book teaches the sentence.",
        ],
      },
      {
        heading: "Market structure first",
        body: [
          "Higher highs and higher lows are an uptrend. Lower highs and lower lows are a downtrend. Ranges are ranges. Until you can mark that in ten seconds, do not look for flags.",
        ],
      },
      {
        heading: "Continuation that continues",
        body: [
          "Flags, pennants, and shallow pullbacks only earn the name if the prior move was real displacement. Tiny chop labelled as a bull flag is how people buy the middle of nothing.",
        ],
        note: {
          tone: "navy",
          title: "Tell",
          text: "If the “flag” lasts longer than the pole, it is not a flag. It is a new range.",
        },
      },
      {
        heading: "Breaks that stick",
        body: [
          "A close beyond structure is a claim. A retest that fails to reclaim is confirmation. Entering the first wick through a level is optional violence — size it like a spike, or wait for the close.",
        ],
      },
      {
        heading: "Candles worth naming",
        body: [
          "Engulfing at a level. Rejection wicks that close back inside the range. Inside bars before expansion. That is the useful list. The rest is trivia that makes you late.",
        ],
        bullets: [
          "Location first, candle second",
          "Close confirms, wick suggests",
          "Opposite candle against your idea is information. Honour it.",
        ],
      },
      {
        heading: "Pattern + family",
        body: [
          "A break-and-retest on V75 is a different animal than a break-and-retest on Boom 300. On spike markets, the pattern is often the grind; the event is the spike. Do not fade a Boom spike with a “rising wedge” you found on M1.",
        ],
      },
    ],
  },
  {
    slug: "trading-psychology",
    title: "Trading Psychology",
    subtitle: "Discipline is the edge",
    seriesNo: "05",
    category: "Trading Psychology",
    size: "medium",
    launchMode: "prelaunch",
    coverUrl: "/covers/trading-psychology.jpg",
    blurb:
      "Process, patience, and control for a market that is always open. How to stop negotiating with yourself after a loss.",
    pages: [
      {
        heading: "The platform is a mirror",
        body: [
          "Synthetic indices will show you your greed at 2 a.m. because they can. If your rules only work when you feel calm, you do not have rules. You have a mood.",
        ],
      },
      {
        heading: "Process over outcome",
        body: [
          "A good trade can lose. A bad trade can win. If you only grade the P&L, you will repeat the bad trade that won and abandon the good trade that lost. Grade the process on paper, the same day.",
        ],
      },
      {
        heading: "The tilt sequence",
        body: [
          "Loss, then larger size, then a market you do not trade, then a revenge spike. You already know this sequence. Write the interrupt: after one loss, five-minute walk. After two, platform closed.",
        ],
        note: {
          tone: "red",
          title: "No debate",
          text: "If you break the daily cap, you are not “seeing if you can recover.” You are practising the habit that ends accounts.",
        },
      },
      {
        heading: "Always-on is a trap",
        body: [
          "A market that never sleeps will invite you to never sleep. Set a session. End the session. The chart will still be there. You will not trade better exhausted; you will trade more.",
        ],
      },
      {
        heading: "Identity",
        body: [
          "You are not “a Boom trader” or “a V75 warrior.” You are a person with a process. When identity gets involved, every loss feels like an insult. Insults get avenged. Accounts get emptied.",
        ],
        bullets: [
          "Session start and end, written",
          "Max trades, written",
          "Review once a week, not once a panic",
        ],
      },
      {
        heading: "The quiet week",
        body: [
          "Some weeks the job is to take two clean ideas and leave. That week will never screenshot well. It is still the work. Profitability is the culture — not activity.",
        ],
      },
    ],
  },
  {
    slug: "boom-crash",
    title: "Boom & Crash",
    subtitle: "Spikes that move the market",
    seriesNo: "06",
    category: "Synthetic Indices",
    size: "full",
    launchMode: "prelaunch",
    coverUrl: "/covers/boom-crash.jpg",
    blurb:
      "A full guide to spike markets: the grind, the event, timing, and the ways traders get run over trying to catch the move they just missed.",
    pages: [
      {
        heading: "Two markets, one family",
        body: [
          "Boom spikes up. Crash spikes down. Between spikes, both grind. If you only study the spike, you will arrive late and leave poorer. If you only study the grind, a spike will one day introduce itself.",
        ],
      },
      {
        heading: "What a spike is",
        body: [
          "A spike is a sudden, large displacement printed as part of the index behaviour — not a news candle. You cannot “predict the next one” on a timer you found in a Telegram channel. You can trade the conditions around them with size that survives a wrong call.",
        ],
        note: {
          tone: "navy",
          title: "Variants",
          text: "Boom/Crash 300, 500, 600, 900, 1000 and the rest differ in spike frequency and typical distance. Learn one pair deeply before you collect them all.",
        },
      },
      {
        heading: "The grind is the job",
        body: [
          "Most of your hours are the grind. Structure, zones, and patience live here. Traders who only hunt spikes sit through chop, then market-buy the event — the most expensive way to participate.",
        ],
      },
      {
        heading: "Trading with the spike",
        body: [
          "After a Boom spike, chasing the wick is usually a gift to the other side. Wait for the first pause. If higher-timeframe structure was already up, the spike may continue as trend. If it was a spike out of a tired range, it may be the whole story.",
        ],
      },
      {
        heading: "Trading against the spike",
        body: [
          "Fading a Crash spike because “it went too far” is how people meet the second spike. Fade only at a mapped higher-timeframe level, with a stop that assumes another leg, and a size that makes that stop boring.",
        ],
        note: {
          tone: "red",
          title: "Do not",
          text: "Do not average into a spike. One idea, one size, one stop.",
        },
      },
      {
        heading: "Timing without superstition",
        body: [
          "Log spike times for the specific index you trade. You will see clusters. Clusters are not a schedule. They are a reason to be at the desk during your session — still with rules.",
        ],
      },
      {
        heading: "Stops and spikes",
        body: [
          "Place stops where the idea is wrong, then size. If the only stop you can afford sits inside the last spike’s range, you cannot afford the trade.",
        ],
      },
      {
        heading: "A simple Boom & Crash desk",
        body: [
          "One Boom, one Crash. H1 bias, M15 level, M5 timing. Max two ideas a session. Screenshot every trade with the reason written on it. Review Sunday. That is a professional week on a spike market.",
        ],
      },
    ],
  },
  {
    slug: "volatility-mastery",
    title: "Volatility Mastery",
    subtitle: "V75 · V100 · V10 · Range",
    seriesNo: "07",
    category: "Synthetic Indices",
    size: "full",
    launchMode: "prelaunch",
    coverUrl: "/covers/volatility-mastery.jpg",
    blurb:
      "How Volatility indices actually behave — from V10 to V100, 1-second variants, ranging days, and the pace that matches your size.",
    pages: [
      {
        heading: "Named volatility",
        body: [
          "The number in the name is not a vibe. It is the personality. V10 will bore a spike-hunter. V75 and V100 will punish a 0.2 lot that felt fine on V10. Match the index to the account, not to the screenshot you liked.",
        ],
      },
      {
        heading: "Standard versus 1s",
        body: [
          "The 1-second variants pack more decision points into the same sitting. That is not “faster money.” That is faster mistakes unless your process is already quiet on the standard index.",
        ],
      },
      {
        heading: "Trend days",
        body: [
          "When V75 decides to run, pullbacks are shallow and feel like they will reverse. They often do not. Trade with the H1. Buy the first decent demand in an uptrend; stop guessing tops because the candle “looks extended.”",
        ],
        note: {
          tone: "green",
          title: "Pace",
          text: "If you cannot watch V75 without clicking, drop to V25 until your hands are boring again.",
        },
      },
      {
        heading: "Range days",
        body: [
          "Volatility indices spend long stretches going nowhere with conviction. Fade the edges only if the range is obvious on M15/H1. In the middle, you are the liquidity.",
        ],
      },
      {
        heading: "V100 is not a personality",
        body: [
          "Wanting V100 because it “moves” is how small accounts volunteer for liquidation. If your dollar risk cannot live with a V100 stop, you do not have a V100 strategy. You have a wish.",
        ],
      },
      {
        heading: "Building a volatility desk",
        body: [
          "Pick one standard index and one backup. Write the session. Write the size. Trade only when H1 and M15 agree. Everything else is a stream you can watch without clicking.",
        ],
        bullets: [
          "V10 / V25 — smaller accounts, cleaner practice",
          "V50 / V75 — the core of this book",
          "V100 — only with size that makes a wide stop ordinary",
        ],
      },
      {
        heading: "Journal what the number did",
        body: [
          "Each week, tag trades by index. You will find you are profitable on one and charitable on another. Drop the charity. Depth on one index beats tourism across ten.",
        ],
      },
    ],
  },
  {
    slug: "step-index",
    title: "Step Index",
    subtitle: "Trade the staircase",
    seriesNo: "08",
    category: "Synthetic Indices",
    size: "medium",
    launchMode: "prelaunch",
    coverUrl: "/covers/step-index.jpg",
    blurb:
      "The staircase market: step size, range, breaks, and why impatience looks extra expensive when price moves in increments.",
    pages: [
      {
        heading: "Price that climbs in counts",
        body: [
          "Step Index does not glide. It prints increments. That changes how you read a “break” and how you place a stop. A stop two steps away is a different decision than a stop that “looks close” on a smooth chart.",
        ],
      },
      {
        heading: "Respect the increment",
        body: [
          "Measure in steps, not in vibes. If your idea needs price to travel twelve steps for a 1:1, and your session only ever gives you four, the idea does not fit the market. Change the idea, not the lot.",
        ],
      },
      {
        heading: "Range on a staircase",
        body: [
          "Steps will walk to a boundary and stall. The stall is information. Breaks that hold beyond the last accepted step are the continuation. Wicks that reject back into the range are the fade — with a stop beyond the break, not inside the last step.",
        ],
        note: {
          tone: "navy",
          title: "Patience",
          text: "Step Index makes boredom visible. That is a gift. Use it. Do not invent a break because you have been watching for twenty minutes.",
        },
      },
      {
        heading: "Breaks",
        body: [
          "A real break accepts a new step and keeps it. Entering the first new print is optional. Entering after acceptance is calmer. Size as if it snaps back one increment — because it often will.",
        ],
      },
      {
        heading: "What not to do",
        body: [
          "Do not scalp every step. You will pay the spread to prove you were present. Trade the range extremes and the accepted breaks. Sit on your hands for the walk in between.",
        ],
      },
      {
        heading: "A Step desk",
        body: [
          "One Step market. Mark yesterday’s accepted high and low. Wait. If nothing accepts a new extreme in your session, you log “no trade” and you still did the work.",
        ],
      },
    ],
  },
  {
    slug: "jump-indices",
    title: "Jump Indices",
    subtitle: "Trade the gap, not the chase",
    seriesNo: "10",
    category: "Synthetic Indices",
    size: "medium",
    launchMode: "prelaunch",
    coverUrl: "/covers/jump-indices.jpg",
    blurb:
      "Jump 10 through Jump 75 — gaps, continuation after the jump, and the discipline to not chase the print you just missed.",
    pages: [
      {
        heading: "A gap with a name",
        body: [
          "Jump indices displace in gaps. The number in the name speaks to how often those jumps appear. Your job is not to catch the jump in the air. Your job is to decide what the chart means after it lands.",
        ],
      },
      {
        heading: "Do not chase the print",
        body: [
          "The jump you just watched is gone. Market-buying the close of a Jump 50 gap because it “will continue” is hope. Wait for the first pause, the first retest, or the first failure. Missed jumps are free.",
        ],
        note: {
          tone: "red",
          title: "Late is expensive",
          text: "If you are in after the jump and your stop is now twice as wide, you are not in the same trade as the person who planned the level.",
        },
      },
      {
        heading: "After the landing",
        body: [
          "Some jumps start a trend. Some jumps are the event. Higher-timeframe structure tells you which. A jump in the direction of H1 through a mapped level is continuation language. A jump into a brick wall of opposite structure is often exhaustion language.",
        ],
      },
      {
        heading: "Stops around gaps",
        body: [
          "Stops inside the gap are decoration. Stops belong beyond the structure that would make the jump a failure. If that stop is too far, the lot shrinks. If the lot cannot shrink anymore, the trade is not yours.",
        ],
      },
      {
        heading: "Jump 10 to Jump 75",
        body: [
          "Start on the slower jump if your account is small. Speed is not a personality trait. It is a cost. Graduate only when your journal shows you can sit through a Jump 10 session without inventing extra clicks.",
        ],
        bullets: ["Jump 10 / 25 — practice the pause", "Jump 50 / 75 — only with boring size"],
      },
      {
        heading: "The rule on the cover",
        body: [
          "Trade the gap, not the chase. Write it above the chart. When you break it, log it as a process fail even if it made money. Especially if it made money.",
        ],
      },
    ],
  },
  {
    slug: "trading-bible",
    title: "The Trading Bible",
    subtitle: "A full guide to synthetic markets",
    seriesNo: "09",
    category: "Full Guides",
    size: "full",
    launchMode: "prelaunch",
    coverUrl: "/covers/trading-bible.jpg",
    blurb:
      "Systems, risk, psychology, and execution in one desk manual — the long-form companion to the rest of the library.",
    pages: [
      {
        heading: "One desk, one manual",
        body: [
          "This book is not a new personality. It is the stapled-together version of how a synthetic desk actually runs: selection, size, session, review. If a chapter here disagrees with a specialist title, the specialist title wins on that market. This wins on process.",
        ],
      },
      {
        heading: "The stack",
        body: [
          "Literacy (101) → size (Risk) → market family (Volatility, Boom & Crash, Step, Jump) → tools (zones, patterns) → psychology on a loop. Skipping size to collect patterns is how people sound educated on the way to a blown account.",
        ],
      },
      {
        heading: "A written system",
        body: [
          "If it is not written, it is not a system. Markets allowed. Session. Risk. Setup definition. Invalidation. Management. Max trades. Review cadence. One page is enough. Ten pages you will not reread is not a system. It is a novel.",
        ],
        note: {
          tone: "navy",
          title: "Minimum viable desk",
          text: "One family. One setup. One risk number. Twenty trades logged. Then — and only then — consider a second setup.",
        },
      },
      {
        heading: "Execution",
        body: [
          "Alerts over staring. Staring manufactures trades. When the alert fires, you have sixty seconds to check higher timeframe, size, and invalidation. If any of the three is missing, you cancel. There is always another alert. The market does not close.",
        ],
      },
      {
        heading: "Management",
        body: [
          "Move to break-even only when the idea has actually been proven — not because you are afraid. Partial at 1R if that is what keeps you from turning winners into spectators. The rule is the rule; mood is not a modifier.",
        ],
      },
      {
        heading: "Review",
        body: [
          "Weekly: screenshots, process grade, size mistakes, markets you had no business in. Monthly: keep, cut, or rewrite one rule. If you never cut a rule, you are not reviewing. You are collecting.",
        ],
      },
      {
        heading: "Community without the crowd",
        body: [
          "SLT Trade Hub is a room, not a signal firehose. Use the community to stay honest. Do not use it to outsource the click. If a bot or a chat changes your size, the system is no longer yours.",
        ],
      },
      {
        heading: "Close the book. Open the journal.",
        body: [
          "Reading feels like progress. Logging twenty trades is progress. Take the 101 map, the risk formula, and one family. Sit the session. End the session. That is the whole religion. Profitability is the culture.",
        ],
      },
    ],
  },
];

export function bookBySlug(slug: string) {
  return CATALOG.find((b) => b.slug === slug);
}

export function onlineCents(size: BookSize) {
  return onlinePrice(size);
}
